# .streamlit/config.toml  → thème & options UI
[theme]
base = "dark"
primaryColor = "#ff7b00"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1F2430"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false